[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true }

[tasks.deps]
description = "Install dependencies"
run = "uv pip install -r requirements.txt"

[tools]
# Template tools
python = "3.14.0"
uv = "latest"
# Operations tools
"aqua:pre-commit/pre-commit" = "latest"
"pipx:cz-conventional-gitmoji" = "latest"
